packages:
  - 'packages/*'

# These keys and yaml-refs can be used when multiple packages need the same version,
# or should be checked and updated as a group. Otherwise just use string refs.
versions:
  eslint: &eslint '^9.13.x'
  html-to-text: &html-to-text '^9.x'
  jest: &jest '^29.x'
  pdfmake: &pdfmake '^0.2.x'
  semver: &semver '^7.x.x'
  typescript-eslint: &typescript-eslint '^8.11.0'
  openid-client: &openid-client '^5.7.1'
  cdk:
    aws-cdk: &aws-cdk '^2.164.0'
    aws-sdk: &aws-sdk '^3.679.0'
    aws-sdk-client-mock: &aws-sdk-client-mock '^4.1.0'
    aws-sdk-node-http-handler: &aws-sdk-node-http-handler '^3.374.0'
    '@aws-quickstart/eks-blueprints': &eks-blueprints '1.15.1'
    cdk-ecr-deployment: &cdk-ecr-deployment '^3.0.136'
    cdk8s: &cdk8s '^2.69.10'
    cdk8s-plus-30: &cdk8s-plus-30 '^2.2.6'
    constructs: &constructs '^10.4.2'
    upsert-slr: &upsert-slr '^1.0.4'
    ts-node: &cdk-ts-node "^10.9.2"
    typescript: &cdk-typescript '~5.6.x'
  cypress:
    "@badeball/cypress-cucumber-preprocessor": &cypress-cucumber-preprocessor '^20.0.6'
    "@bahmutov/cypress-esbuild-preprocessor": &cypress-esbuild-preprocessor '^2.2.1'
    cypress: &cypress-cypress '^13.11.0'
    cypress-wait-until: &cypress-wait-until '^3.0.1'
  # check https://angular.dev/reference/versions
  angular18:
    angular: &angular18 '^18.2.x'
    angular-eslint: &angular18-eslint '^18.4.x'
    angular-gridster2: &angular18-gridster "^18.0.1"
    karma: &angular18-karma '^6.3.0'
    karma-allure-reporter: &angular18-karma-allure-reporter '^1.4.6'
    karma-chrome-launcher: &angular18-karma-chrome-launcher '^3.2.0'
    karma-coverage: &angular18-karma-coverage '^2.2.1'
    karma-jasmine: &angular18-karma-jasmine '^5.1.0'
    karma-jasmine-html-reporter: &angular18-karma-jasmine-html-reporter '^2.1.0'
    karma-junit-reporter: &angular18-karma-junit-reporter '^2.0.1'
    ng-packagr: &angular18-ng-packagr '^18.2.x'
    ngx-cookie-service: &angular18-ngx-cookie-service '^18.0.0'
    ngx-sub-form: &angular18-ngx-sub-form '^11.0.0'
    puppeteer: &angular18-puppeteer '^23.5.2'
    rxjs: &angular18-rxjs '^6.5.3 || ^7.4.0'
    typescript: &angular18-typescript '>=5.4.0 <5.6.0'
    types-jasmine: &angular18-types-jasmine '~4.3.6'
    zone.js: &angular18-zonejs '~0.14.10'
    apollo-angular: &angular18-apollo-angular '7.2.1'

catalog:
  '@eslint/eslintrc': '^3.1.0'
  '@eslint/js': *eslint
  '@redocly/cli': &redocly '^1.25.9'
  '@redocly/openapi-core': *redocly
  '@types/html-to-text': *html-to-text
  '@types/jest': *jest
  '@types/luxon': '^3.4.2'
  '@types/node': '^22.13.1'
  '@types/pdfmake': *pdfmake
  '@types/semver': *semver
  '@typescript-eslint/eslint-plugin': *typescript-eslint
  '@typescript-eslint/parser': *typescript-eslint
  '@typescript-eslint/type-utils': *typescript-eslint
  '@typescript-eslint/typescript-estree': *typescript-eslint
  allure-jest: '^2.15.1'
  axios: '^1.7.7'
  domhandler: '^5.0.3'
  esbuild: '^0.24.0'
  eslint-config-google: '^0.14.0'
  eslint-config-prettier: '^9.1.0'
  eslint-plugin-editorconfig: '^4.0.3'
  eslint-plugin-prettier: '^5.2.1'
  eslint: *eslint
  handlebars: '^4.7.8'
  htmlparser2: '^9.0.0'
  hono: '^4.6.5'
  html-to-text: *html-to-text
  luxon: '^3.5.0'
  jest: *jest
  jest-junit: '^16.0.0'
  jwt-decode: '^4.0.0'
  ngx-quill: '^26.0.8'
  openapi-typescript: '^7.4.1'
  pdfmake: *pdfmake
  prettier-eslint: '^16.3.0'
  prettier: '^3.3.3'
  quill-delta: '^5.1.0'
  quill: '^2.0.2'
  semver: *semver
  stylelint-config-standard-scss: '^13.1.0'
  stylelint: '^16.9.0'
  tslib: '^2.7.0'
  tslog: '^4.9.3'
  ts-deepmerge: '^7.0.1'
  ts-jest: *jest
  ts-md5: '^1.3.1'
  ts-node: *cdk-ts-node
  typescript: *cdk-typescript
  typescript-eslint: *typescript-eslint
  uuidv7: '^1.0.2'
  graphql: '^16'
  '@apollo/client': '^3.0.0'
  openid-client: *openid-client

catalogs:
  cdk:
    aws-cdk: *aws-cdk
    aws-cdk-lib: *aws-cdk
    '@aws-cdk/cloudformation-diff': *aws-cdk
    '@aws-cdk/cx-api': *aws-cdk
    '@aws-quickstart/eks-blueprints': *eks-blueprints
    '@aws-sdk/core': *aws-sdk
    '@aws-sdk/client-eks': *aws-sdk
    '@aws-sdk/client-s3': *aws-sdk
    '@aws-sdk/client-ssm': *aws-sdk
    '@aws-sdk/client-sts': *aws-sdk
    '@aws-sdk/node-http-handler': *aws-sdk-node-http-handler
    '@aws-sdk/types': *aws-sdk
    aws-sdk-client-mock: *aws-sdk-client-mock
    cdk-ecr-deployment: *cdk-ecr-deployment
    cdk8s: *cdk8s
    cdk8s-plus-30: *cdk8s-plus-30
    constructs: *constructs
    ts-node: *cdk-ts-node
    typescript: *cdk-typescript
    upsert-slr: *upsert-slr
  cypress:
    '@aws-sdk/client-s3': *aws-sdk
    '@aws-sdk/client-sts': *aws-sdk
    '@aws-sdk/credential-providers': *aws-sdk
    '@badeball/cypress-cucumber-preprocessor': *cypress-cucumber-preprocessor
    '@bahmutov/cypress-esbuild-preprocessor': *cypress-esbuild-preprocessor
    cypress: *cypress-cypress
    cypress-wait-until: *cypress-wait-until
    typescript: *cdk-typescript
  angular18:
    # angular packages
    '@angular/animations': *angular18
    '@angular/cdk': *angular18
    '@angular/cli': *angular18
    '@angular/common': *angular18
    '@angular/compiler': *angular18
    '@angular/compiler-cli': *angular18
    '@angular-devkit/build-angular': *angular18
    '@angular/core': *angular18
    '@angular/forms': *angular18
    '@angular/material': *angular18
    '@angular/material-luxon-adapter': *angular18
    '@angular/platform-browser': *angular18
    '@angular/platform-browser-dynamic': *angular18
    '@angular/router': *angular18
    # angular-eslint packages
    '@angular-eslint/builder': *angular18-eslint
    '@angular-eslint/eslint-plugin': *angular18-eslint
    '@angular-eslint/eslint-plugin-template': *angular18-eslint
    '@angular-eslint/schematics': *angular18-eslint
    '@angular-eslint/template-parser': *angular18-eslint
    'angular-eslint': *angular18-eslint
    # other angular-related dependencies
    '@types/jasmine': *angular18-types-jasmine
    angular-gridster2: *angular18-gridster
    karma: *angular18-karma
    karma-allure-reporter: *angular18-karma-allure-reporter
    karma-chrome-launcher: *angular18-karma-chrome-launcher
    karma-coverage: *angular18-karma-coverage
    karma-jasmine: *angular18-karma-jasmine
    karma-jasmine-html-reporter: *angular18-karma-jasmine-html-reporter
    karma-junit-reporter: *angular18-karma-junit-reporter
    ng-packagr: *angular18-ng-packagr
    ngx-cookie-service: *angular18-ngx-cookie-service
    ngx-sub-form: *angular18-ngx-sub-form
    puppeteer: *angular18-puppeteer
    rxjs: *angular18-rxjs
    typescript: *angular18-typescript
    zone.js: *angular18-zonejs
    apollo-angular: *angular18-apollo-angular
